### ISSUE TITLE
No music from plex found

### ISSUE THREAD

**Issue by Cruiser13** [jjdenhertog/spotify-to-plex#18]
Hi,
let me first thank you for this great app, I have been looking for a spotify -> plex connection for ages! Awesome work!

I seem to be stuck in the setup process, maybe you can give me a hand here.

I connected to spotify and plex accounts. And I can select my plex server (both IP and domain assigned):
<img width="372" alt="Image" src="https://github.com/user-attachments/assets/9921d386-4d18-4618-b81c-0fb80390a8c2" />
But there seems to be no next step here, no matter which one I'm choosing.

If I head to the spotify settings, I can select playlists and they load fine but all playlists show no titles in my plex (and the songs are definately there!):

![Image](https://github.com/user-attachments/assets/001f8e7d-c4ee-4ff0-b101-6d88f180af35)

So my guess would be that the sync with my plex server is somehow incomplete and maybe I'm missing a step here?

The interface looks a little bit messed up too:
![Image](https://github.com/user-attachments/assets/fc9dfb12-d997-46cc-950e-160b0a143aa1)

But buttons and funcionality are there (on hover at least):

![Image](https://github.com/user-attachments/assets/998dbfc8-2ab2-4843-9203-b9f0276ff751)

Any guidance would be highly appreciated!

**Comment by KINGLIFER** [comment]
Same

**Comment by jjdenhertog** [comment]
@KINGLIFER @koiralasandesh  Interesting, I've never seen this behavior. You should be seeing plex servers that start with an ip-address. Can you maybe share the output (or parts of it) of what you are seeing on this page?

http://**[[IP_ADDRESS]]**:9030/api/plex/resources

**Comment by Cruiser13** [comment]
@jjdenhertog opening the page brings up JSON in the following format:
```json
[{"name":"MyServer","id":"0d43.......31","connections":[{"uri":"http://192.168.178.33:32400","local":true},{"uri":"http://plex.domain:80","local":false},{"uri":"https://plex.domain","local":false}]}]
```

If I switching to the local IP ( http://192.168.178.33:32400 in my case) instead of the domain I can not continue further in the screen and still have the display issues but it suddently starts to find songs! That would work in my case - I'd leave that issue open for KINGLIFER though.

**Comment by jjdenhertog** [comment]
@Cruiser13 @KINGLIFER This might have been related to #22. I just pushed a new version. Can you try again? You might need to switch server (and switch back again) for it to work again.

**Comment by KINGLIFER** [comment]
I'll check now

**Comment by Cruiser13** [comment]
@jjdenhertog thank you so much for looking into it! The new version sadly did not change something for me. Using the local IP the plex tracks will be found, using the domain (with or without the :80 at the end) it will not find any tracks.
Display issues do also still exist.
But I'd be fine with using the local IP as described above.

**Comment by jjdenhertog** [comment]
Thanks for checking! Good to know that for now it's only possible to use ip addresses

**Comment by firmlyundecided** [comment]
+1 confirming that using local IP works for music search, while using a proxy domain for plex results in no song matches. running in Synology DSM Container Manager
